# Generated by Django 2.1.5 on 2019-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=255)),
                ('wx_openid', models.CharField(default='', max_length=255)),
                ('nickName', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=30)),
                ('avatarUrl', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=2)),
                ('language', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('province', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=15)),
                ('session_key', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
