# Generated by Django 2.1.5 on 2019-02-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_openid', models.CharField(default='', max_length=255)),
                ('from_address', models.CharField(default='', max_length=30)),
                ('des_address', models.CharField(default='', max_length=30)),
                ('leave_time', models.DateTimeField(null=True)),
                ('seats_count', models.PositiveIntegerField(default=0)),
                ('demo', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=20)),
                ('contact_phone', models.CharField(default='', max_length=30)),
                ('contact_wechat_account', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
