# Generated by Django 2.1.5 on 2019-02-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20190214_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_info',
            name='seats_count',
            field=models.PositiveIntegerField(default=0, max_length=10),
        ),
    ]
